### PR TITLE
Add support for Linux

### PR DESCRIPTION
**Pull request by frankcarey**
# DONT MERGE YET!

.. but feedback and testing welcome :)
Relates to #50 

There are some improvements to be made, but this is at least working on ubuntu 14.04 for me with the following:

docker 1.10.1
docker-machine 0.6.0
docker-compose 1.6.0

to make it run: 
`docker-machine-nfs default --nfs-config="(rw,sync,no_root_squash,no_subtree_check)" --shared-folder=/home/fcarey/docker-share --force`

### CODE REVIEW

**Comment by tonivdv** [comment]
:+1:

**Comment by dharizza** [comment]
Hi, 
Using this script worked for me on Linux Mint 17.3.
Thank you!

**Comment by tonivdv** [comment]
@frankcarey Are you still gonna work on this? Or can I close this one?

**Comment by tonivdv** [comment]
I'm closing this PR. Feel free to reopen if you want to finish it. Cheers

**Pull request closed without merging**
